enum Message {
  TEXT_ERROR = 'Произошла ошибка, повторите попытку позже',
  CODE_SEND_ERROR = 'Не удалось отправить код',
  INCORRECT_CODE_ERROR = 'Некорректный код',
  PLACEHOLDER_CONFIRMATION_CODE = 'Код подтверждения',
  PLACEHOLDER_EMAIL = 'Адрес эл. почты',
  BUTTON_CONTINUE = 'Продолжить',
  BUTTON_BACK = 'Назад',
  BUTTON_LOGIN = 'Войти',
  NO_NETWORK_CONNECTION = 'Отсутствует подключение к сети',
  BUTTON_RECONNECT = 'Обновить',
  NO_SUBSCRIPTION = 'Нет подписки',
  TITLE_SUBSCRIPTIONS = 'Подписки на изменения в расписании',
  TITLE_SUBSCRIPTION = 'Подписка на изменения в расписании',
  TITLE_COMMUNICATION_CHANNELS = 'Способы отправки оповещений',
  TEXT_CC_VK = 'ВКонтакте',
  TEXT_CC_TELEGRAM = 'Telegram',
  TEXT_CC_EMAIL = 'Эл. почта',
  BUTTON_UPDATE = 'Обновить',
  BUTTON_LOGOUT = 'Выйти из системы',
  TITLE_LOGIN = 'Вход',
  TITLE_ADD_CHANNEL = 'Добавление способа отправки оповещений',
  TITLE_EDIT_CHANNEL = 'Редактирование способа отправки оповещений',
  TITLE_SUBMIT_CODE = 'На указанный адрес отправлен код подтверждения',
  PLACEHOLDER_VK_ID = 'VK ID',
  PLACEHOLDER_TG_ID = 'Telegram ID',
  PLACEHOLDER_SEARCH = 'Поиск',
  BUTTON_UNDERSTAND = 'Понятно',
  TEXT_SUB_GROUP = 'Группа',
  TEXT_SUB_TEACHER = 'Преподаватель',
  BUTTON_APPLY = 'Применить',
}

export default Message;
